# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

schedules:
- cron: "0 */8 * * *" # DAMN BUG!!!!!!!!!!!!!!!!!!!!!!!!!
  displayName: Schedule Build
  branches:
    include:
    - master
  always: true

pool:
  vmImage: 'macOS-latest'

steps:

- task: Bash@3
  displayName: Prepare Pipelines
  inputs:
    targetType: 'inline'
    script: |
      #!/bin/bash
      cd ../b
      git clone https://github.com/MuntashirAkon/DPCIManager.git
      cd DPCIManager
      git clone https://github.com/pciutils/pciids.git
      mv pciids/pci.ids .
      url=$(xcodebuild -configuration Release -arch x86_64 -scheme dspci -showBuildSettings | grep TARGET_BUILD_DIR | awk {'print $NF'})
      xcodebuild -configuration Release -arch x86_64 -scheme dspci
      mkdir ../../a/Artifacts
      cp -f $url/dspci ../../a/Artifacts
      cd ../b
      git clone https://github.com/acidanthera/OpenCorePkg.git
      cd OpenCorePkg/Utilities/macserial
      make
      cp -f ./macserial ../../../../../a/Artifacts
      ls $(Build.ArtifactStagingDirectory)/Artifacts
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'vps'
    sourceFolder: '$(Build.ArtifactStagingDirectory)/Artifacts'
    contents: '**'
    targetFolder: '/var/www/downloads/tools'
    readyTimeout: '20000'